apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: zidanpyon/tickets
          env:
            - name: JWT_KEY
              value: "NicoNicoNii"
            - name: MONGO_URI
              value: "mongodb://tickets-mongo-service:27017/tickets"
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "64Mi"
              cpu: "0.1"
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-service
spec:
  selector:
    app: tickets
  ports:
    - name: tickets

      protocol: TCP
      port: 3000
      targetPort: 3000
